name: flutter_assessment
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.2 <4.0.0'

dependencies: 
  json_annotation: ^4.6.0
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.7
  image_picker: ^0.8.7+5
  get: 4.6.5
  buttons_tabbar: ^1.3.7+1
  flutter_slidable: ^3.0.0
  get_storage: ^2.1.1
  flutter_easyloading: ^3.0.5
  url_launcher: ^6.1.12
  email_validator: ^2.1.17
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  build_runner: ^2.0.0
  json_serializable: ^6.3.1

  flutter_test: 
    sdk: flutter



flutter: 
  assets:
    - .env
    - assets/svg/

  uses-material-design: true

